### ISSUE TITLE
final fixes

### ISSUE THREAD

**Issue by poopsicles** [hngx-org/Eagles-food-backend#35]
- ~~some endpoints return `Org` or `organisation_id` fix that, make things consistent~~
- let POST api/lunch/send just take one receiver instead of a list
- ~~/api/user/all doesn't return all the users?~~

**Comment by poopsicles** [comment]
- make it so everyone that uses our api is added to a default "Eagles Organisation"
- add lunch credit balance to GET /api/user/profile
- lunches are unlimited, so anyone can send
- listing all the people in the org should return just their name and id (excluding the originator)

**Comment by poopsicles** [comment]
fixed with #[22e2ff5](https://github.com/hngx-org/Eagles-food-backend/commit/22e2ff58c44214c1de5b5eae46f00a61ca746312)

**Comment by poopsicles** [comment]
2 fixed with [7cb5646](https://github.com/hngx-org/Eagles-food-backend/commit/7cb5646aceb63e03bc7e21e789a40202aebda856)

**Comment by poopsicles** [comment]
add api for lunch withdrawal

**Comment by IEdiong** [comment]
Api for lunch withdrawal has been done and documented.
